[phases.setup]
nixPkgs = ["python311", "pip"]
cmds = ["ln -sf /nix/store/*/bin/python3.11 /usr/local/bin/python"]

[phases.build]
cmds = ["python -m pip install -r requirements.txt"]

[phases.install]
cmds = []

[start]