[phases.setup]
nixPkgs = ["python311", "pip"]
cmds = ["ln -sf /nix/store/*/bin/python3.11 /usr/local/bin/python"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c 'print(\"Build completed\")'"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"